<a href="https://colab.research.google.com/github/danny77beltran/Matrices/blob/main/MatricesDeber.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import numpy as np

# Definir dos matrices A y B de 3x3
A = np.array([[2, 4, 6,],
              [1, 3, 5,],
              [0, -1, 2,]])

B = np.array([[3, 2, 1,],
              [4 , 0, -2,],
              [1, 3, 5,]
              ])

print("Matriz A:\n", A)
print("\nMatriz B:\n", B)
'''
# ------------------------------
# Suma de matrices
# ------------------------------
suma = A + B
print("\n Suma (A + B):\n", suma)
'''
# ------------------------------
#  Resta de matrices
# ------------------------------
'''

resta = A - B
print("\n Resta (A - B):\n", resta)
'''

# ------------------------------
# Multiplicación por un escalar
# ------------------------------
escalar = 2
producto_escalar = escalar * A
print(f"\n Multiplicación por escalar ({escalar} * A):\n", producto_escalar)

# ------------------------------
#  Multiplicación matricial
# ------------------------------
producto = np.dot(A, B)   # o A @ B
print("\n Producto matricial (A * B):\n", producto)

valor = A[0,0] * B[0,2] + A[0,1] * B[1,2] + A[0,2] * B[2,2]
print("El valor de C[0,2] = ",valor)

# ------------------------------
# Matriz transpuesta
# ------------------------------
'''
transpuesta = A.T
print("\n Transpuesta de A (Aᵀ):\n", transpuesta)
'''

Matriz A:
 [[ 2  4  6]
 [ 1  3  5]
 [ 0 -1  2]]

Matriz B:
 [[ 3  2  1]
 [ 4  0 -2]
 [ 1  3  5]]

 Multiplicación por escalar (2 * A):
 [[ 4  8 12]
 [ 2  6 10]
 [ 0 -2  4]]

 Producto matricial (A * B):
 [[28 22 24]
 [20 17 20]
 [-2  6 12]]
El valor de C[0,2] =  24


'\ntranspuesta = A.T\nprint("\n Transpuesta de A (Aᵀ):\n", transpuesta)\n'